version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root # Run as root to install additional packages if necessary
    ports:
      - "8080:8080" # Jenkins web UI port
      - "50000:50000" # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # For Docker inside Jenkins
    environment:
      JENKINS_OPTS: --prefix=/jenkins # Optional, to serve Jenkins from /jenkins path

volumes:
  jenkins_home:
